### ISSUE TITLE
Reporte de Práctica 3

### ISSUE THREAD

**Issue by Nancy-0714** [SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-companion-ai#1]
[Mockup de eventos de interfaz grafica.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-companion-ai/files/14315421/Mockup.de.eventos.de.interfaz.grafica.pdf)

Integrantes :
Evelyn Santiago Victoria
Vanessa Cruz Ortiz
Nancy Olivera Santiago

**Comment by Daniel-Velasco-Lopez** [comment]
En base a la rúbrica, han obtenido un total de 80 puntos de 100.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
